import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'vi';

type Theme = 'light' | 'dark' | 'system';

interface SettingsContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  timezone: string;
  setTimezone: (tz: string) => void;
  theme: Theme;
  setTheme: (theme: Theme) => void;
  geminiApiKey: string;
  setGeminiApiKey: (key: string) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    projects: 'Projects',
    partners: 'Partners',
    calendar: 'Calendar',
    reports: 'Reports',
    settings: 'Settings',
    search_placeholder: 'Search projects, partners, tasks...',
    notifications: 'Notifications',
    mark_all_read: 'Mark all as read',
    view_all_notifications: 'View all notifications',
    no_notifications: 'No notifications yet',
    new_event: 'New Event',
    create_event: 'Create Event',
    edit_event: 'Edit Event',
    save_changes: 'Save Changes',
    cancel: 'Cancel',
    event_title: 'Event Title',
    date: 'Date',
    time: 'Time',
    type: 'Type',
    description: 'Description',
    language_region: 'Language & Region',
    preferred_language: 'Preferred Language',
    time_zone: 'Time Zone',
    save_preferences: 'Save Preferences',
    planning: 'Planning',
    welcome_back: 'Welcome back',
    total_revenue: 'Total Revenue',
    active_projects: 'Active Projects',
    completed: 'Completed',
    pending_tasks: 'Pending Tasks',
    new_report: 'New Report',
    revenue_overview: 'Revenue Overview',
    recent_projects: 'Recent Projects',
    view_all_projects: 'View All Projects',
    last_6_months: 'Last 6 Months',
    last_year: 'Last Year',
    generate_report: 'Generate Report',
    report_type: 'Report Type',
    time_range: 'Time Range',
    include_in_report: 'Include in Report',
    generate_pdf: 'Generate PDF',
    monthly_summary: 'Monthly Summary',
    project_specific: 'Project Specific',
    last_30_days: 'Last 30 Days',
    last_quarter: 'Last Quarter',
    custom_range: 'Custom Range',
    revenue_charts: 'Revenue Charts',
    project_progress: 'Project Progress',
    payment_status: 'Payment Status',
    partner_contributions: 'Partner Contributions',
    generating: 'Generating...',
    timeline: 'Timeline',
    team: 'Team',
    ai_assistant: 'AI Assistant',
    team_members: 'Team Members',
    workload: 'Workload',
    project_timeline: 'Project Timeline',
    status: 'Status',
    assignee: 'Assignee',
    due_date: 'Due Date',
    priority: 'Priority',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    'kanban.title': 'Kanban Board',
    'kanban.subtitle': 'Manage tasks and track progress visually.',
    'kanban.searchPlaceholder': 'Search tasks...',
    'kanban.status.todo': 'Todo',
    'kanban.status.inprogress': 'In Progress',
    'kanban.status.review': 'Review',
    'kanban.status.done': 'Done',
    kanban: 'Kanban Board',
    add_task: 'Add Task',
    notes: 'Personal Notes',
    financial_hub: 'Financial Hub',
    daily_log: 'Daily Log',
    // Projects page
    projects_subtitle: 'Manage your freelance and corporate web development projects.',
    projects_sort_label: 'Sort by',
    projects_sort_created_desc: 'Date created (newest)',
    projects_sort_created_asc: 'Date created (oldest)',
    projects_sort_deadline_asc: 'Deadline (soonest)',
    projects_sort_deadline_desc: 'Deadline (latest)',
    projects_sort_name_asc: 'Name (A–Z)',
    projects_sort_name_desc: 'Name (Z–A)',
    projects_sort_progress_desc: 'Progress (high to low)',
    projects_sort_amount_desc: 'Budget (high to low)',
    filter_all: 'All',
    type_freelance: 'Freelance',
    type_corporate: 'Corporate',
    type_internal: 'Internal',
    type_personal: 'Personal',
    status_in_progress: 'In Progress',
    status_review: 'Review',
    status_completed: 'Completed',
    status_maintenance: 'Maintenance',
    status_on_hold: 'On Hold',
    status_cancelled: 'Cancelled',
    progress_label: 'Progress',
    amount_label: 'Amount',
    payment_label: 'Payment',
    resources_label: 'Resources',
    pd_resource_tags: 'Resource tags',
    pd_add_resource_tag: 'Add tag',
    no_resources_added: 'No resources added',
    additional_info: 'Additional Info',
    not_applicable: 'N/A',
    details: 'Details',
    col_project: 'Project',
    col_type: 'Type',
    col_progress: 'Progress',
    col_payment: 'Payment',
    col_amount: 'Amount',
    partner_avatar_alt: 'Partner',
    member_prefix: 'Member',
    edit_project: 'Edit Project',
    project_name: 'Project Name',
    client_company: 'Client / Company',
    ph_project_name: 'e.g. E-commerce Website',
    ph_client: 'e.g. Fashion Hub',
    project_type: 'Project Type',
    amount_vnd: 'Amount (VND)',
    amount_usd: 'Amount (USD)',
    progress_percent: 'Progress (%)',
    payment_unpaid: 'Unpaid',
    payment_partial: 'Partial',
    payment_paid: 'Paid',
    assigned_member: 'Assigned Member',
    no_member: 'No Member',
    technical_details: 'Technical Details',
    hosting_info: 'Hosting Info',
    demo_link: 'Demo Link',
    live_link: 'Live Link',
    ph_hosting: 'e.g. Vercel, AWS, Netlify',
    ph_demo_url: 'https://staging.example.com',
    ph_live_url: 'https://example.com',
    custom_fields: 'Custom Fields',
    add_field: 'Add Field',
    field_label: 'Label',
    field_value: 'Value',
    ph_field_label: 'e.g. Server IP',
    ph_field_value: 'e.g. 192.168.1.1',
    no_custom_fields: 'No custom fields added yet.',
    delete_project: 'Delete Project',
    update_project: 'Update Project',
    create_project: 'Create Project',
    err_save_project: 'Failed to save project. Please try again.',
    err_delete_project: 'Failed to delete project. Please try again.',
    delete_project_confirm: 'Delete project "{{name}}"? This cannot be undone.',
    // Project details page (ProjectDetails.tsx)
    pd_project_not_found: 'Project Not Found',
    pd_back_to_projects: 'Back to Projects',
    pd_created_line: '{{client}} • Created on {{date}}',
    pd_edit_header_hint: 'This route is the project editor — update the fields below and click Save.',
    pd_save_success: 'Changes saved.',
    pd_section_detail_edit: 'Project information',
    pd_section_detail_edit_hint:
      'Logo uploads as soon as you choose a file; name, progress, payment, and deadline save when you click Save.',
    pd_modal_all_project_fields: 'All fields in dialog…',
    pd_logo_section: 'Project logo',
    pd_logo_showing: 'Showing project logo.',
    pd_logo_none: 'No logo yet. Upload a logo image.',
    pd_logo_upload: 'Upload logo',
    pd_logo_hint: 'Square image recommended, max ~2MB.',
    pd_stat_budget: 'Budget',
    pd_stat_team: 'Team',
    pd_members: '{{count}} members',
    pd_weekly_activity: 'Weekly Activity',
    pd_tasks_completed: 'Tasks Completed',
    pd_weekday_mon: 'Mon',
    pd_weekday_tue: 'Tue',
    pd_weekday_wed: 'Wed',
    pd_weekday_thu: 'Thu',
    pd_weekday_fri: 'Fri',
    pd_weekday_sat: 'Sat',
    pd_weekday_sun: 'Sun',
    pd_recent_tasks: 'Recent Tasks',
    pd_no_tasks: 'No tasks yet. Add one to get started!',
    pd_project_team: 'Project Team',
    pd_me: 'Me',
    pd_you_role: 'Team Member',
    pd_live_website: 'Live Website',
    pd_hosting_inline: 'Hosting: {{info}}',
    pd_project_files: 'Project Files',
    pd_no_files: 'No files uploaded yet.',
    pd_remove_member_aria: 'Remove team member',
    pd_assign_member: 'Assign Member',
    pd_add_new_task: 'Add New Task',
    pd_task_title: 'Task Title',
    pd_task_placeholder: 'What needs to be done?',
    pd_add_project_file: 'Add Project File',
    pd_add_file: 'Add File',
    pd_add_file_tag: 'Add item',
    pd_select_file: 'Choose file',
    pd_no_file_selected: 'No file selected',
    pd_file_name: 'File Name',
    pd_file_size: 'File Size',
    ph_pd_file_name: 'e.g. Design_v1.fig',
    ph_pd_file_size: 'e.g. 1.2 MB',
    pd_stat_deadline: 'Deadline',
    // Timeline page
    timeline_subtitle: 'Visualize project schedules and milestones.',
    filter_by_status: 'Filter by Status',
    timeline_hide_project: 'Hide this project',
    timeline_hidden_single: '1 project hidden',
    timeline_hidden_plural: '{{count}} projects hidden',
    show_all: 'Show all',
    no_projects_found: 'No projects found.',
    timeline_demo_period: 'Mar 2026 – Jun 2026',
    timeline_avg_duration: 'Avg. Duration',
    timeline_avg_days: '42 Days',
    timeline_on_schedule: 'On Schedule',
    timeline_critical_path: 'Critical Path',
    timeline_stat_projects: '{{count}} Projects',
    // Team page
    team_subtitle: 'Manage your team and monitor their workload.',
    team_search_placeholder: 'Search members...',
    team_add_member: 'Add Member',
    team_edit_member: 'Edit Member',
    team_remove: 'Remove',
    team_err_save: 'Failed to save: {{msg}}',
    team_err_add: 'Failed to add member: {{msg}}',
    team_confirm_remove: 'Are you sure you want to remove this team member?',
    team_avatar_invalid: 'Only JPG, PNG, GIF, and WebP images are allowed.',
    team_avatar_too_large: 'File size must be less than 2MB.',
    team_add_new_title: 'Add New Member',
    team_edit_title: 'Edit Team Member',
    team_profile_picture: 'Profile Picture',
    team_avatar_hint: 'PNG, JPG or GIF. Max 2MB.',
    upload: 'Upload',
    team_full_name: 'Full Name',
    team_role: 'Role',
    team_email: 'Email',
    team_zalo: 'Zalo Number',
    ph_team_name: 'John Doe',
    ph_team_role: 'Developer, Designer, etc.',
    ph_team_email: 'john@example.com',
    ph_zalo: '0912345678',
    ph_zalo_edit: 'e.g. 0912345678',
    team_card_projects: '{{count}} Projects',
    team_card_tasks: '{{count}} Tasks',
    contact_email: 'Email',
    avatar_preview_alt: 'Avatar preview',
    // Calendar page
    calendar_subtitle: 'Deadlines and project milestones.',
    weekday_sun: 'Sun',
    weekday_mon: 'Mon',
    weekday_tue: 'Tue',
    weekday_wed: 'Wed',
    weekday_thu: 'Thu',
    weekday_fri: 'Fri',
    weekday_sat: 'Sat',
    cal_ph_title: "What's happening?",
    cal_select_date: 'Select date',
    cal_ph_description: 'Add more details...',
    event_type_general: 'General',
    err_save_event: 'Failed to save event. Please try again.',
    confirm_delete_event: 'Delete this event?',
    err_delete_event: 'Failed to delete event.',
    cal_success_updated: 'Event updated successfully.',
    cal_success_created: 'Event created successfully.',
    cal_success_deleted: 'Event deleted successfully.',
    delete: 'Delete',
    // Planning page
    planning_subtitle: 'Roadmap, learning goals, and personal growth.',
    planning_add_goal: 'Add Goal',
    planning_edit_goal: 'Edit Goal',
    planning_add_modal_title: 'Add New Goal',
    planning_goal_title: 'Goal Title',
    ph_planning_goal: 'Learn a new skill...',
    ph_planning_details: 'Details about your goal...',
    planning_target_date: 'Target Date',
    planning_move_to: 'Move to {{status}}',
    planning_empty: 'No items yet',
    planning_delete_confirm: 'Are you sure you want to delete this goal?',
    plan_col_todo: 'Todo',
    plan_col_doing: 'Doing',
    plan_col_done: 'Done',
    planning_update_goal: 'Update Goal',
    // Notes page
    notes_subtitle: 'Store useful information, snippets, and reminders.',
    notes_drag_hint: 'Drag cards by the handle to reorder.',
    notes_drag_disabled: 'Set category to All and clear search to reorder notes.',
    notes_drag_handle: 'Drag to reorder',
    notes_new: 'New Note',
    notes_search_ph: 'Search notes...',
    notes_edit: 'Edit',
    notes_actions_menu: 'More actions',
    notes_empty_title: 'No notes found',
    notes_empty_hint: 'Try adjusting your search or category filter.',
    notes_modal_new: 'New Note',
    notes_modal_edit: 'Edit Note',
    note_title: 'Title',
    ph_note_title: 'Note title...',
    note_category: 'Category',
    ph_note_category: 'Pick a suggestion or type your own…',
    note_category_hint: 'You can reuse suggestions or enter any new category name.',
    note_pin_label: 'Pin Note',
    note_state_pinned: 'Pinned',
    note_action_pin: 'Pin to Top',
    note_content: 'Content',
    ph_note_content: 'Write your note here...',
    note_save: 'Save Note',
    note_update: 'Update Note',
    note_cat_general: 'General',
    note_cat_work: 'Work',
    note_cat_personal: 'Personal',
    note_cat_reference: 'Reference',
    note_cat_ideas: 'Ideas',
    err_note_save: 'Could not save the note. Please try again.',
    // Daily log page
    daily_subtitle: 'Track your daily work and progress.',
    daily_stat_days_logged: 'Days Logged',
    daily_stat_hours: 'Hours Worked',
    daily_stat_streak: 'Day Streak',
    daily_today: 'Today',
    daily_saved: 'Saved',
    daily_what_done: 'What did you work on today?',
    ph_daily_acc: 'e.g. Finished login API...',
    daily_add_item: 'Add task',
    daily_notes_title: 'Additional notes',
    ph_daily_notes: 'Thoughts, ideas, notes...',
    daily_blockers_title: 'Any blockers?',
    ph_daily_blockers: 'What is slowing you down?',
    daily_save_log: 'Save Log',
    err_daily_save: 'Failed to save log. Please try again.',
    daily_details: 'Details',
    daily_hours: 'Hours worked',
    daily_project: 'Project',
    daily_project_placeholder: '— Select project —',
    daily_mood_today: "Today's mood",
    mood_happy: 'Happy',
    mood_productive: 'Productive',
    mood_neutral: 'Neutral',
    mood_tired: 'Tired',
    mood_stressed: 'Stressed',
    daily_this_week: 'This Week',
    daily_no_logs_week: 'No logs this week yet',
    daily_no_preview: 'No notes',
    // Settings page
    settings_subtitle: 'Manage your account preferences and application settings.',
    settings_tab_profile: 'Profile',
    settings_tab_notifications: 'Notifications',
    settings_tab_security: 'Security',
    settings_tab_appearance: 'Appearance',
    settings_tab_language: 'Language',
    settings_tab_system: 'System',
    settings_public_profile: 'Public Profile',
    settings_upload_new: 'Upload New',
    settings_email_address: 'Email Address',
    settings_bio: 'Bio',
    ph_settings_bio: 'Tell us about yourself...',
    settings_err_auth: 'Not authenticated',
    settings_profile_ok: 'Profile updated successfully!',
    settings_profile_err: 'Failed to save profile. Please try again.',
    settings_notif_section: 'Notification Settings',
    settings_email_notif_title: 'Email Notifications',
    settings_email_notif_desc: 'Receive email updates about your projects and tasks.',
    settings_test_email_card: 'Test Email',
    settings_test_email_desc: 'Send a test email to verify your email configuration is working.',
    settings_send_test_email: 'Send Test Email',
    settings_test_email_sent: 'Test email sent! Check your inbox.',
    settings_test_email_fail: 'Failed to send email: {{msg}}',
    settings_test_email_error: 'Error: {{msg}}',
    settings_notif_ok: 'Notification preferences saved!',
    settings_notif_err: 'Failed to save preferences. Please try again.',
    settings_security_privacy: 'Security & Privacy',
    settings_change_password: 'Change Password',
    settings_current_password: 'Current Password',
    settings_new_password: 'New Password',
    settings_forgot_password: 'Forgot password?',
    settings_2fa_section: 'Two-Factor Authentication',
    settings_sms_2fa: 'SMS Authentication',
    settings_sms_2fa_desc: 'Secure your account with a code sent to your phone.',
    settings_2fa_enabled_btn: 'Enabled',
    settings_2fa_enable_btn: 'Enable',
    settings_update_security: 'Save Security Settings',
    pwd_new_required: 'Please enter a new password.',
    pwd_min_8: 'Password must be at least 8 characters.',
    pwd_upper: 'Password must contain at least one uppercase letter.',
    pwd_lower: 'Password must contain at least one lowercase letter.',
    pwd_number: 'Password must contain at least one number.',
    pwd_updated: 'Password updated successfully!',
    pwd_update_fail: 'Failed to update password: {{msg}}',
    settings_appearance: 'Appearance Settings',
    settings_interface_theme: 'Interface Theme',
    theme_light: 'Light',
    theme_dark: 'Dark',
    theme_system: 'System',
    settings_accent_color: 'Accent Color',
    settings_system_title: 'System Settings',
    settings_danger_zone: 'Danger Zone',
    settings_reset_desc:
      'Resetting application data will clear all your projects, tasks, and settings stored in this browser. This action cannot be undone.',
    settings_reset_confirm: 'Are you sure you want to reset all data? This will restore the app to its initial state.',
    settings_reset_ok: 'Application data has been reset.',
    settings_reset_btn: 'Reset All Data',
    settings_2fa_modal_title: 'Setup SMS Authentication',
    settings_phone_step_title: 'Enter your phone number',
    settings_phone_step_desc: "We'll send a 6-digit code to verify your identity.",
    settings_phone_label: 'Phone Number',
    ph_settings_phone: '+84 123 456 789',
    settings_send_verification: 'Send Verification Code',
    settings_verify_step_title: 'Verify your phone',
    settings_verify_step_desc: 'Enter the 6-digit code sent to {{phone}}',
    settings_verif_code_label: 'Verification Code',
    settings_verify_enable_btn: 'Verify & Enable',
    settings_back_phone: 'Back to phone number',
    settings_2fa_success: 'Two-factor authentication enabled successfully!',
    settings_prefs_saved: 'Preferences saved! Language: {{lang}}, Timezone: {{tz}}.',
    lang_name_en: 'English (US)',
    lang_name_vi: 'Tiếng Việt',
    partner_portal_title: 'Project status for partners',
    partner_portal_subtitle: 'Work progress and payment status — no sign-in required.',
    partner_login_cta: 'Log in',
    partner_no_projects: 'No projects to display yet.',
    partner_tasks_done: '{{done}} / {{total}} tasks completed',
    partner_load_error: 'Could not load data.',
    partner_loading: 'Loading…',
    partner_portal_footer: 'Read-only overview. Sign in to manage projects.',
    app_name: 'DevFlow',
    not_found_title: 'Page not found',
    not_found_description: "We couldn't find that page. It may have been moved or the link is wrong.",
    not_found_back_home: 'Partner progress',
    not_found_open_app: 'Open app',
    logout: 'Log out',
  },
  vi: {
    dashboard: 'Bảng điều khiển',
    projects: 'Dự án',
    partners: 'Đối tác',
    partners_lower: 'đối tác',
    calendar: 'Lịch',
    reports: 'Báo cáo',
    settings: 'Cài đặt',
    search_placeholder: 'Tìm kiếm dự án, đối tác, nhiệm vụ...',
    notifications: 'Thông báo',
    mark_all_read: 'Đánh dấu tất cả đã đọc',
    view_all_notifications: 'Xem tất cả thông báo',
    no_notifications: 'Chưa có thông báo nào',
    new_event: 'Sự kiện mới',
    create_event: 'Tạo sự kiện',
    edit_event: 'Chỉnh sửa sự kiện',
    save_changes: 'Lưu thay đổi',
    cancel: 'Hủy',
    event_title: 'Tiêu đề sự kiện',
    date: 'Ngày',
    time: 'Giờ',
    type: 'Loại',
    description: 'Mô tả',
    language_region: 'Ngôn ngữ & Khu vực',
    preferred_language: 'Ngôn ngữ ưu tiên',
    time_zone: 'Múi giờ',
    save_preferences: 'Lưu tùy chọn',
    planning: 'Lập kế hoạch',
    welcome_back: 'Chào mừng trở lại',
    total_revenue: 'Tổng doanh thu',
    active_projects: 'Dự án đang chạy',
    completed: 'Đã hoàn thành',
    pending_tasks: 'Nhiệm vụ chờ',
    new_report: 'Báo cáo mới',
    revenue_overview: 'Tổng quan doanh thu',
    recent_projects: 'Dự án gần đây',
    view_all_projects: 'Xem tất cả dự án',
    last_6_months: '6 tháng qua',
    last_year: 'Năm qua',
    generate_report: 'Tạo báo cáo',
    report_type: 'Loại báo cáo',
    time_range: 'Khoảng thời gian',
    include_in_report: 'Bao gồm trong báo cáo',
    generate_pdf: 'Tạo PDF',
    monthly_summary: 'Tóm tắt hàng tháng',
    project_specific: 'Dự án cụ thể',
    last_30_days: '30 ngày qua',
    last_quarter: 'Quý trước',
    custom_range: 'Tùy chỉnh',
    revenue_charts: 'Biểu đồ doanh thu',
    project_progress: 'Tiến độ dự án',
    payment_status: 'Trạng thái thanh toán',
    partner_contributions: 'Đóng góp của đối tác',
    generating: 'Đang tạo...',
    timeline: 'Lộ trình',
    team: 'Đội ngũ',
    ai_assistant: 'Trợ lý AI',
    team_members: 'Thành viên',
    workload: 'Khối lượng công việc',
    project_timeline: 'Lộ trình dự án',
    status: 'Trạng thái',
    assignee: 'Người phụ trách',
    due_date: 'Hạn chót',
    priority: 'Ưu tiên',
    high: 'Cao',
    medium: 'Trung bình',
    low: 'Thấp',
    'kanban.title': 'Bảng Kanban',
    'kanban.subtitle': 'Quản lý nhiệm vụ và theo dõi tiến độ trực quan.',
    'kanban.searchPlaceholder': 'Tìm kiếm nhiệm vụ...',
    'kanban.status.todo': 'Cần làm',
    'kanban.status.inprogress': 'Đang làm',
    'kanban.status.review': 'Đang duyệt',
    'kanban.status.done': 'Hoàn thành',
    kanban: 'Bảng Kanban',
    add_task: 'Thêm nhiệm vụ',
    notes: 'Ghi chú cá nhân',
    financial_hub: 'Trung tâm Tài chính',
    daily_log: 'Nhật ký hàng ngày',
    // Projects page
    projects_subtitle: 'Quản lý các dự án phát triển web freelance và doanh nghiệp của bạn.',
    projects_sort_label: 'Sắp xếp theo',
    projects_sort_created_desc: 'Ngày tạo (mới nhất)',
    projects_sort_created_asc: 'Ngày tạo (cũ nhất)',
    projects_sort_deadline_asc: 'Deadline (gần nhất)',
    projects_sort_deadline_desc: 'Deadline (xa nhất)',
    projects_sort_name_asc: 'Tên (A–Z)',
    projects_sort_name_desc: 'Tên (Z–A)',
    projects_sort_progress_desc: 'Tiến độ (cao → thấp)',
    projects_sort_amount_desc: 'Ngân sách (cao → thấp)',
    filter_all: 'Tất cả',
    type_freelance: 'Freelance',
    type_corporate: 'Doanh nghiệp',
    type_internal: 'Nội bộ',
    type_personal: 'Cá nhân',
    status_in_progress: 'Đang thực hiện',
    status_review: 'Đang duyệt',
    status_completed: 'Hoàn thành',
    status_maintenance: 'Bảo trì',
    status_on_hold: 'Tạm dừng',
    status_cancelled: 'Đã hủy',
    progress_label: 'Tiến độ',
    amount_label: 'Số tiền',
    payment_label: 'Thanh toán',
    resources_label: 'Tài nguyên',
    pd_resource_tags: 'Thẻ tài nguyên',
    pd_add_resource_tag: 'Thêm thẻ',
    no_resources_added: 'Chưa có tài nguyên',
    additional_info: 'Thông tin thêm',
    not_applicable: 'Không có',
    details: 'Chi tiết',
    col_project: 'Dự án',
    col_type: 'Loại',
    col_progress: 'Tiến độ',
    col_payment: 'Thanh toán',
    col_amount: 'Số tiền',
    partner_avatar_alt: 'Đối tác',
    member_prefix: 'Thành viên',
    edit_project: 'Sửa dự án',
    project_name: 'Tên dự án',
    client_company: 'Khách hàng / Công ty',
    ph_project_name: 'vd: Website thương mại điện tử',
    ph_client: 'vd: Fashion Hub',
    project_type: 'Loại dự án',
    amount_vnd: 'Số tiền (VNĐ)',
    amount_usd: 'Amount (USD)',
    progress_percent: 'Tiến độ (%)',
    payment_unpaid: 'Chưa thanh toán',
    payment_partial: 'Một phần',
    payment_paid: 'Đã thanh toán',
    assigned_member: 'Thành viên phụ trách',
    no_member: 'Chưa gán',
    technical_details: 'Chi tiết kỹ thuật',
    hosting_info: 'Hosting',
    demo_link: 'Link demo',
    live_link: 'Link chính thức',
    ph_hosting: 'vd: Vercel, AWS, Netlify',
    ph_demo_url: 'https://staging.example.com',
    ph_live_url: 'https://example.com',
    custom_fields: 'Trường tùy chỉnh',
    add_field: 'Thêm trường',
    field_label: 'Nhãn',
    field_value: 'Giá trị',
    ph_field_label: 'vd: IP máy chủ',
    ph_field_value: 'vd: 192.168.1.1',
    no_custom_fields: 'Chưa có trường tùy chỉnh.',
    delete_project: 'Xóa dự án',
    update_project: 'Cập nhật dự án',
    create_project: 'Tạo dự án',
    err_save_project: 'Không thể lưu dự án. Vui lòng thử lại.',
    err_delete_project: 'Không thể xóa dự án. Vui lòng thử lại.',
    delete_project_confirm: 'Xóa dự án "{{name}}"? Hành động này không thể hoàn tác.',
    // Project details page (ProjectDetails.tsx)
    pd_project_not_found: 'Không tìm thấy dự án',
    pd_back_to_projects: 'Về danh sách dự án',
    pd_created_line: '{{client}} • Tạo ngày {{date}}',
    pd_edit_header_hint: 'Đây là trang chỉnh sửa dự án — cập nhật các mục bên dưới rồi bấm Lưu.',
    pd_save_success: 'Đã lưu thay đổi.',
    pd_section_detail_edit: 'Thông tin dự án',
    pd_section_detail_edit_hint:
      'Logo cập nhật ngay khi chọn tệp; tên, tiến độ, thanh toán và hạn chót lưu khi bấm Lưu.',
    pd_modal_all_project_fields: 'Tất cả trường (hộp thoại)…',
    pd_logo_section: 'Logo dự án',
    pd_logo_showing: 'Đang hiển thị logo dự án.',
    pd_logo_none: 'Chưa có logo, hãy tải ảnh logo lên.',
    pd_logo_upload: 'Tải logo lên',
    pd_logo_hint: 'Khuyến nghị ảnh vuông, tối đa ~2MB.',
    pd_stat_budget: 'Ngân sách',
    pd_stat_team: 'Đội',
    pd_members: '{{count}} thành viên',
    pd_weekly_activity: 'Hoạt động theo tuần',
    pd_tasks_completed: 'Nhiệm vụ đã xong',
    pd_weekday_mon: 'T2',
    pd_weekday_tue: 'T3',
    pd_weekday_wed: 'T4',
    pd_weekday_thu: 'T5',
    pd_weekday_fri: 'T6',
    pd_weekday_sat: 'T7',
    pd_weekday_sun: 'CN',
    pd_recent_tasks: 'Nhiệm vụ gần đây',
    pd_no_tasks: 'Chưa có nhiệm vụ. Thêm một nhiệm vụ để bắt đầu!',
    pd_project_team: 'Đội dự án',
    pd_me: 'Tôi',
    pd_you_role: 'Thành viên',
    pd_live_website: 'Website chính',
    pd_hosting_inline: 'Hosting: {{info}}',
    pd_project_files: 'Tệp dự án',
    pd_no_files: 'Chưa có tệp nào được tải lên.',
    pd_remove_member_aria: 'Gỡ thành viên khỏi dự án',
    pd_assign_member: 'Gán thành viên',
    pd_add_new_task: 'Thêm nhiệm vụ mới',
    pd_task_title: 'Tiêu đề nhiệm vụ',
    pd_task_placeholder: 'Cần làm gì?',
    pd_add_project_file: 'Thêm tệp dự án',
    pd_add_file: 'Thêm tệp',
    pd_add_file_tag: 'Thêm thẻ',
    pd_select_file: 'Chọn tệp',
    pd_no_file_selected: 'Chưa chọn tệp',
    pd_file_name: 'Tên tệp',
    pd_file_size: 'Dung lượng',
    ph_pd_file_name: 'vd: Design_v1.fig',
    ph_pd_file_size: 'vd: 1.2 MB',
    pd_stat_deadline: 'Hạn chót',
    // Timeline page
    timeline_subtitle: 'Xem lịch trình và các mốc dự án.',
    filter_by_status: 'Lọc theo trạng thái',
    timeline_hide_project: 'Ẩn dự án này',
    timeline_hidden_single: 'Đã ẩn 1 dự án',
    timeline_hidden_plural: 'Đã ẩn {{count}} dự án',
    show_all: 'Hiện tất cả',
    no_projects_found: 'Không có dự án nào.',
    timeline_demo_period: 'Thg 3 2026 – Thg 6 2026',
    timeline_avg_duration: 'Thời gian TB',
    timeline_avg_days: '42 ngày',
    timeline_on_schedule: 'Đúng tiến độ',
    timeline_critical_path: 'Đường găng',
    timeline_stat_projects: '{{count}} dự án',
    // Team page
    team_subtitle: 'Quản lý đội ngũ và theo dõi khối lượng công việc.',
    team_search_placeholder: 'Tìm thành viên...',
    team_add_member: 'Thêm thành viên',
    team_edit_member: 'Sửa thành viên',
    team_remove: 'Gỡ',
    team_err_save: 'Không thể lưu: {{msg}}',
    team_err_add: 'Không thể thêm thành viên: {{msg}}',
    team_confirm_remove: 'Bạn có chắc muốn xóa thành viên này khỏi đội?',
    team_avatar_invalid: 'Chỉ chấp nhận ảnh JPG, PNG, GIF hoặc WebP.',
    team_avatar_too_large: 'Dung lượng tệp phải nhỏ hơn 2MB.',
    team_add_new_title: 'Thêm thành viên mới',
    team_edit_title: 'Sửa thành viên',
    team_profile_picture: 'Ảnh đại diện',
    team_avatar_hint: 'PNG, JPG hoặc GIF. Tối đa 2MB.',
    upload: 'Tải lên',
    team_full_name: 'Họ và tên',
    team_role: 'Vai trò',
    team_email: 'Email',
    team_zalo: 'Số Zalo',
    ph_team_name: 'Nguyễn Văn A',
    ph_team_role: 'Lập trình viên, Thiết kế...',
    ph_team_email: 'ten@example.com',
    ph_zalo: '0912345678',
    ph_zalo_edit: 'vd: 0912345678',
    team_card_projects: '{{count}} dự án',
    team_card_tasks: '{{count}} nhiệm vụ',
    contact_email: 'Email',
    avatar_preview_alt: 'Xem trước ảnh đại diện',
    // Calendar page
    calendar_subtitle: 'Hạn chót và mốc quan trọng của dự án.',
    weekday_sun: 'CN',
    weekday_mon: 'T2',
    weekday_tue: 'T3',
    weekday_wed: 'T4',
    weekday_thu: 'T5',
    weekday_fri: 'T6',
    weekday_sat: 'T7',
    cal_ph_title: 'Sự kiện gì sắp diễn ra?',
    cal_select_date: 'Chọn ngày',
    cal_ph_description: 'Thêm chi tiết...',
    event_type_general: 'Chung',
    err_save_event: 'Không thể lưu sự kiện. Vui lòng thử lại.',
    confirm_delete_event: 'Xóa sự kiện này?',
    err_delete_event: 'Không thể xóa sự kiện.',
    cal_success_updated: 'Đã cập nhật sự kiện.',
    cal_success_created: 'Đã tạo sự kiện.',
    cal_success_deleted: 'Đã xóa sự kiện.',
    delete: 'Xóa',
    // Planning page
    planning_subtitle: 'Lộ trình, mục tiêu học tập và phát triển bản thân.',
    planning_add_goal: 'Thêm mục tiêu',
    planning_edit_goal: 'Sửa mục tiêu',
    planning_add_modal_title: 'Thêm mục tiêu mới',
    planning_goal_title: 'Tiêu đề mục tiêu',
    ph_planning_goal: 'Học một kỹ năng mới...',
    ph_planning_details: 'Chi tiết về mục tiêu...',
    planning_target_date: 'Ngày mục tiêu',
    planning_move_to: 'Chuyển sang {{status}}',
    planning_empty: 'Chưa có mục nào',
    planning_delete_confirm: 'Bạn có chắc muốn xóa mục tiêu này?',
    plan_col_todo: 'Cần làm',
    plan_col_doing: 'Đang làm',
    plan_col_done: 'Hoàn thành',
    planning_update_goal: 'Cập nhật mục tiêu',
    // Notes page
    notes_subtitle: 'Lưu thông tin, đoạn mã và lời nhắc hữu ích.',
    notes_drag_hint: 'Kéo thẻ bằng nút ⋮⋮ để sắp xếp.',
    notes_drag_disabled: 'Chọn "Tất cả" và xóa ô tìm kiếm để kéo sắp xếp ghi chú.',
    notes_drag_handle: 'Kéo để sắp xếp',
    notes_new: 'Ghi chú mới',
    notes_search_ph: 'Tìm ghi chú...',
    notes_edit: 'Sửa',
    notes_actions_menu: 'Thêm thao tác',
    notes_empty_title: 'Không có ghi chú',
    notes_empty_hint: 'Thử đổi từ khóa hoặc bộ lọc danh mục.',
    notes_modal_new: 'Ghi chú mới',
    notes_modal_edit: 'Sửa ghi chú',
    note_title: 'Tiêu đề',
    ph_note_title: 'Tiêu đề ghi chú...',
    note_category: 'Danh mục',
    ph_note_category: 'Chọn gợi ý hoặc gõ tên mới…',
    note_category_hint: 'Bạn có thể chọn gợi ý hoặc nhập bất kỳ tên danh mục nào.',
    note_pin_label: 'Ghim ghi chú',
    note_state_pinned: 'Đã ghim',
    note_action_pin: 'Ghim lên đầu',
    note_content: 'Nội dung',
    ph_note_content: 'Viết nội dung tại đây...',
    note_save: 'Lưu ghi chú',
    note_update: 'Cập nhật ghi chú',
    note_cat_general: 'Chung',
    note_cat_work: 'Công việc',
    note_cat_personal: 'Cá nhân',
    note_cat_reference: 'Tham khảo',
    note_cat_ideas: 'Ý tưởng',
    err_note_save: 'Không thể lưu ghi chú. Vui lòng thử lại.',
    // Daily log page
    daily_subtitle: 'Ghi chép công việc và tiến độ hàng ngày.',
    daily_stat_days_logged: 'Ngày đã log',
    daily_stat_hours: 'Giờ làm việc',
    daily_stat_streak: 'Streak ngày',
    daily_today: 'Hôm nay',
    daily_saved: 'Đã lưu',
    daily_what_done: 'Hôm nay bạn làm gì?',
    ph_daily_acc: 'VD: Hoàn thành API login...',
    daily_add_item: 'Thêm nhiệm vụ',
    daily_notes_title: 'Ghi chú thêm',
    ph_daily_notes: 'Những suy nghĩ, ý tưởng, ghi chú...',
    daily_blockers_title: 'Có gì cản trở?',
    ph_daily_blockers: 'Những thứ làm chậm tiến độ...',
    daily_save_log: 'Lưu nhật ký',
    err_daily_save: 'Không thể lưu nhật ký. Vui lòng thử lại.',
    daily_details: 'Chi tiết',
    daily_hours: 'Giờ làm việc',
    daily_project: 'Dự án',
    daily_project_placeholder: '— Chọn dự án —',
    daily_mood_today: 'Tâm trạng hôm nay',
    mood_happy: 'Vui vẻ',
    mood_productive: 'Hiệu quả',
    mood_neutral: 'Bình thường',
    mood_tired: 'Mệt',
    mood_stressed: 'Căng thẳng',
    daily_this_week: 'Tuần này',
    daily_no_logs_week: 'Chưa có log nào tuần này',
    daily_no_preview: 'Không có ghi chú',
    // Settings page
    settings_subtitle: 'Quản lý tài khoản và tùy chỉnh ứng dụng.',
    settings_tab_profile: 'Hồ sơ',
    settings_tab_notifications: 'Thông báo',
    settings_tab_security: 'Bảo mật',
    settings_tab_appearance: 'Giao diện',
    settings_tab_language: 'Ngôn ngữ',
    settings_tab_system: 'Hệ thống',
    settings_public_profile: 'Hồ sơ công khai',
    settings_upload_new: 'Tải ảnh mới',
    settings_email_address: 'Địa chỉ email',
    settings_bio: 'Giới thiệu',
    ph_settings_bio: 'Giới thiệu ngắn về bạn...',
    settings_err_auth: 'Chưa đăng nhập',
    settings_profile_ok: 'Đã cập nhật hồ sơ!',
    settings_profile_err: 'Không thể lưu hồ sơ. Vui lòng thử lại.',
    settings_notif_section: 'Cài đặt thông báo',
    settings_email_notif_title: 'Thông báo qua email',
    settings_email_notif_desc: 'Nhận email về dự án và nhiệm vụ của bạn.',
    settings_test_email_card: 'Email thử',
    settings_test_email_desc: 'Gửi email thử để kiểm tra cấu hình gửi mail.',
    settings_send_test_email: 'Gửi email thử',
    settings_test_email_sent: 'Đã gửi email thử! Kiểm tra hộp thư.',
    settings_test_email_fail: 'Không gửi được email: {{msg}}',
    settings_test_email_error: 'Lỗi: {{msg}}',
    settings_notif_ok: 'Đã lưu tùy chọn thông báo!',
    settings_notif_err: 'Không thể lưu tùy chọn. Vui lòng thử lại.',
    settings_security_privacy: 'Bảo mật & quyền riêng tư',
    settings_change_password: 'Đổi mật khẩu',
    settings_current_password: 'Mật khẩu hiện tại',
    settings_new_password: 'Mật khẩu mới',
    settings_forgot_password: 'Quên mật khẩu?',
    settings_2fa_section: 'Xác thực hai lớp',
    settings_sms_2fa: 'Xác thực SMS',
    settings_sms_2fa_desc: 'Bảo vệ tài khoản bằng mã gửi đến điện thoại.',
    settings_2fa_enabled_btn: 'Đã bật',
    settings_2fa_enable_btn: 'Bật',
    settings_update_security: 'Lưu cài đặt bảo mật',
    pwd_new_required: 'Vui lòng nhập mật khẩu mới.',
    pwd_min_8: 'Mật khẩu phải có ít nhất 8 ký tự.',
    pwd_upper: 'Mật khẩu phải có ít nhất một chữ hoa.',
    pwd_lower: 'Mật khẩu phải có ít nhất một chữ thường.',
    pwd_number: 'Mật khẩu phải có ít nhất một chữ số.',
    pwd_updated: 'Đã cập nhật mật khẩu!',
    pwd_update_fail: 'Không thể đổi mật khẩu: {{msg}}',
    settings_appearance: 'Cài đặt giao diện',
    settings_interface_theme: 'Chủ đề giao diện',
    theme_light: 'Sáng',
    theme_dark: 'Tối',
    theme_system: 'Theo hệ thống',
    settings_accent_color: 'Màu nhấn',
    settings_system_title: 'Cài đặt hệ thống',
    settings_danger_zone: 'Vùng nguy hiểm',
    settings_reset_desc:
      'Đặt lại dữ liệu sẽ xóa toàn bộ dự án, nhiệm vụ và cài đặt lưu trên trình duyệt này. Không thể hoàn tác.',
    settings_reset_confirm:
      'Bạn có chắc muốn đặt lại toàn bộ dữ liệu? Ứng dụng sẽ trở về trạng thái ban đầu.',
    settings_reset_ok: 'Đã đặt lại dữ liệu ứng dụng.',
    settings_reset_btn: 'Đặt lại toàn bộ dữ liệu',
    settings_2fa_modal_title: 'Thiết lập xác thực SMS',
    settings_phone_step_title: 'Nhập số điện thoại',
    settings_phone_step_desc: 'Chúng tôi sẽ gửi mã 6 số để xác minh.',
    settings_phone_label: 'Số điện thoại',
    ph_settings_phone: '+84 123 456 789',
    settings_send_verification: 'Gửi mã xác nhận',
    settings_verify_step_title: 'Xác minh điện thoại',
    settings_verify_step_desc: 'Nhập mã 6 số đã gửi đến {{phone}}',
    settings_verif_code_label: 'Mã xác nhận',
    settings_verify_enable_btn: 'Xác minh và bật',
    settings_back_phone: 'Quay lại nhập số điện thoại',
    settings_2fa_success: 'Đã bật xác thực hai lớp!',
    settings_prefs_saved: 'Đã lưu! Ngôn ngữ: {{lang}}, múi giờ: {{tz}}.',
    lang_name_en: 'English (US)',
    lang_name_vi: 'Tiếng Việt',
    // Header
    settings_nav: 'Cài đặt',
    logout: 'Đăng xuất',
    view: 'Xem',
    profile: 'Hồ sơ',
    // Sidebar
    current_plan: 'Gói hiện tại',
    pro_developer: 'Pro Developer',
    monthly_goal: 'mục tiêu hàng tháng',
    // Notification titles & descriptions
    'notif.new_project.title': 'Dự án mới được giao',
    'notif.new_project.desc': 'Bạn được giao dự án "E-commerce Platform"',
    'notif.payment.title': 'Đã nhận thanh toán',
    'notif.payment.desc': 'Thanh toán cho "Mobile App" đã được xác nhận',
    'notif.deadline.title': 'Hạn chót sắp đến',
    'notif.deadline.desc': '"Dashboard UI" đến hạn trong 24 giờ',
    'notif.2mins': '2 phút trước',
    'notif.1hour': '1 giờ trước',
    'notif.5hours': '5 giờ trước',
    // Search
    no_results: 'Không tìm thấy kết quả nào cho',
    // Dashboard
    quick_actions: 'Thao tác nhanh',
    new_project: 'Dự án mới',
    invite_partner: 'Mời đối tác',
    schedule: 'Lên lịch',
    analytics: 'Phân tích',
    daily_summary: 'Tóm tắt hôm nay',
    projects_today: 'Dự án đang hoạt động',
    manage_team: 'Quản lý đội ngũ',
    no_team_members: 'Chưa có thành viên nào',
    add_first_member: 'Thêm thành viên đầu tiên',
    members_total: 'thành viên',
    project_count_one: 'Dự án',
    project_count_other: 'Dự án',
    view_details: 'Xem chi tiết',
    // Report modal
    last_year_vi: 'Năm qua',
    select_at_least_one: 'Vui lòng chọn ít nhất một mục để bao gồm trong báo cáo.',
    report_generated: 'Thành công! Báo cáo đã được tạo.',
    copy_clipboard: 'Đã sao chép liên kết báo cáo!',
    share_report: 'Chia sẻ báo cáo',
    // Misc
    app_name: 'DevFlow',
    partner_portal_title: 'Tiến độ dự án',
    partner_portal_subtitle: 'Theo dõi tiến độ xử lý và trạng thái thanh toán — không cần đăng nhập.',
    partner_login_cta: 'Đăng nhập',
    partner_no_projects: 'Chưa có dự án để hiển thị.',
    partner_tasks_done: '{{done}} / {{total}} công việc hoàn thành',
    partner_load_error: 'Không tải được dữ liệu.',
    partner_loading: 'Đang tải…',
    partner_portal_footer: 'Chỉ xem. Đăng nhập để quản lý dự án.',
    not_found_title: 'Không tìm thấy trang',
    not_found_description: 'Không có trang này. Có thể đã đổi địa chỉ hoặc liên kết không đúng.',
    not_found_back_home: 'Trang tiến độ',
    not_found_open_app: 'Mở ứng dụng',
  }
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export function SettingsProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  const [timezone, setTimezoneState] = useState(() => {
    return localStorage.getItem('app_timezone') || 'Asia/Ho_Chi_Minh';
  });

  const [theme, setThemeState] = useState<Theme>(() => {
    const saved = localStorage.getItem('app_theme');
    return (saved as Theme) || 'light';
  });

  const [geminiApiKey, setGeminiApiKeyState] = useState(() => {
    return import.meta.env.VITE_GEMINI_API_KEY || localStorage.getItem('gemini_api_key') || '';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const setTimezone = (tz: string) => {
    setTimezoneState(tz);
    localStorage.setItem('app_timezone', tz);
  };

  const setTheme = (t: Theme) => {
    setThemeState(t);
    localStorage.setItem('app_theme', t);
    document.documentElement.classList.toggle('dark', t === 'dark' || (t === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches));
  };

  const setGeminiApiKey = (key: string) => {
    setGeminiApiKeyState(key);
    localStorage.setItem('gemini_api_key', key);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <SettingsContext.Provider value={{ language, setLanguage, timezone, setTimezone, theme, setTheme, geminiApiKey, setGeminiApiKey, t }}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (context === undefined) {
    throw new Error('useSettings must be used within a SettingsProvider');
  }
  return context;
}
